FROM denoland/deno:2-alpine AS base
WORKDIR /app

FROM base AS install
COPY deno.json deno.json
COPY apps/web/deno.json apps/web/deno.json
COPY packages/website/deno.json packages/website/deno.json
COPY packages/render/deno.json packages/render/deno.json
COPY packages/database/deno.json packages/database/deno.json
COPY packages/utils/deno.json packages/utils/deno.json
RUN deno install

FROM install AS build
COPY . .
RUN deno task build:web

FROM base AS runner
RUN addgroup -S web && adduser -S -G web web
COPY --from=build --chown=web:web /app/apps/web ./apps/web
COPY --from=build /app/deno.json ./deno.json
COPY --from=build /app/packages ./packages

USER web
EXPOSE 8000

CMD ["task", "-c", "apps/web/deno.json", "start"]
